# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.2
# matrix:
#   allow_failures:
#     - julia: nightly
notifications:
  email: false
git:
  depth: 99999999

# after_script:
#   - julia -e 'using Pkg, TraitSimulation; cd(joinpath(dirname(pathof(TraitSimulation)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'


jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using TraitSimulation; include(joinpath(dirname(pathof(TraitSimulation)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip  
